/* audio.h: Real-time audio generation API.
 *
 * SPDX-FileCopyrightText: 2025 Robota UFSC
 * SPDX-License-Identifier: MIT
 */

#include <stdbool.h>

/**
 * Setup the audio generation.
 * 
 * @return Whether the setup was successful.
 */
bool setup_audio(void);

/**
 * Generates the next samples of audio.
 * 
 * This function should be called often and will block until new samples can be generated.
 */
void process_audio(void);

/**
 * This function will set the frequency and amplitude of the signal generated by the next calls to process_audio().
 */
void set_audio_params(float frequency, float amplitude);
